services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

volumes:
  postgres_data:
