# Generated by Django 5.2 on 2025-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
